//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MasterStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MasterStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MasterStrings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string btnLogOutText {
            get {
                return ResourceManager.GetString("btnLogOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add users.
        /// </summary>
        internal static string lbAddUsersText {
            get {
                return ResourceManager.GetString("lbAddUsersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User list.
        /// </summary>
        internal static string lbDisplayUsersText {
            get {
                return ResourceManager.GetString("lbDisplayUsersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository - .
        /// </summary>
        internal static string lblRepoText {
            get {
                return ResourceManager.GetString("lblRepoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string lbSettingsText {
            get {
                return ResourceManager.GetString("lbSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit users.
        /// </summary>
        internal static string lbUpdateUsersText {
            get {
                return ResourceManager.GetString("lbUpdateUsersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string projektString {
            get {
                return ResourceManager.GetString("projektString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataBase.
        /// </summary>
        internal static string repoOptionDB {
            get {
                return ResourceManager.GetString("repoOptionDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextFile.
        /// </summary>
        internal static string repoOptionTextFile {
            get {
                return ResourceManager.GetString("repoOptionTextFile", resourceCulture);
            }
        }
    }
}
